import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

import { buildAttestationChecksum } from "@/lib/edtech/attestation";
import type { CampaignMetrics } from "@/lib/types";

export function buildCampaignCsv(rows: Array<Record<string, string | number | boolean>>): string {
  if (rows.length === 0) {
    return "";
  }

  const headers = Object.keys(rows[0]);
  const lines = [headers.join(",")];

  for (const row of rows) {
    const values = headers.map((header) => {
      const raw = `${row[header] ?? ""}`;
      return `"${raw.replaceAll('"', '""')}"`;
    });
    lines.push(values.join(","));
  }

  return lines.join("\n");
}

export async function buildSignedPdfSummary(input: {
  orgName: string;
  campaignName: string;
  metrics: CampaignMetrics;
  generatedAtIso: string;
  generatedBy: string;
  supplementalLines?: string[];
}): Promise<{ bytes: Uint8Array; checksum: string }> {
  const checksum = buildAttestationChecksum(input);

  const pdfDoc = await PDFDocument.create();
  const page = pdfDoc.addPage([612, 792]);
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const titleFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  page.drawText("AI Compliance Training Evidence Summary", {
    x: 48,
    y: 748,
    size: 20,
    font: titleFont,
    color: rgb(0.07, 0.14, 0.24),
  });

  const lines = [
    `Organization: ${input.orgName}`,
    `Campaign: ${input.campaignName}`,
    `Generated by: ${input.generatedBy}`,
    `Generated at: ${input.generatedAtIso}`,
    `Assignments total: ${input.metrics.assignmentsTotal}`,
    `Assignments completed: ${input.metrics.assignmentsCompleted}`,
    `Completion rate: ${Math.round(input.metrics.completionRate * 100)}%`,
    `Attestation rate: ${Math.round(input.metrics.attestationRate * 100)}%`,
    `Average score: ${Math.round(input.metrics.averageScore)}%`,
    ...(input.supplementalLines ?? []),
    `Checksum: ${checksum}`,
  ];

  lines.forEach((line, index) => {
    page.drawText(line, {
      x: 48,
      y: 700 - index * 28,
      size: 12,
      font,
      color: rgb(0.16, 0.2, 0.27),
    });
  });

  const bytes = await pdfDoc.save();
  return { bytes, checksum };
}
